### ISSUE TITLE
Windows Defender identify it as a virus threat

### ISSUE THREAD

**Issue by andreysay** [NebuTech/BTMiner_NebuTech#49]
Trojan:Win32/Zpevdo.A
SEVERE |Detected with Windows Defender Antivirus

Windows Defender Antivirus detects and removes this threat.

This threat can perform a number of actions of a malicious hacker's choice on your PC.

Find out ways that malware can get on your PC.

What to do now
Use the following free Microsoft software to detect and remove this threat:

Windows Defender  for Windows 10 and Windows 8.1, or Microsoft Security Essentials for Windows 7 and Windows Vista
Microsoft Safety Scanner
You should also run a full scan. A full scan might find other hidden malware.

Get more help
You can also see our advanced troubleshooting page for more help.

If you’re using Windows XP, see our Windows XP end of support page.
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Zpevdo.A&ThreatID=-2147240153

**Comment by LongLifeLove** [comment]
The same problem with you！

**Comment by nebutech-admin** [comment]
The miner software uses DRM techniques to prevent itself to be tampered. Anti-virus softwares sometimes classify them as viruses because the techniques are used to obfuscate malicious software.
BTMiner_NebuTech is not a piece of malicious software. You do have to add an exception in Windows Defender to use it.
