### ISSUE TITLE
Hashrate drops

### ISSUE THREAD

**Issue by Crowbcat** [NebuTech/BTMiner_NebuTech#69]
Updated to latest 9th version. I receive these hashrate drops for some reason. Running on 17 machines. Mostly 1070s.

What could be the reason? Haven't experienced these on 8th and 6th versions.

<img width="1067" alt="screen shot 2018-08-29 at 13 50 57" src="https://user-images.githubusercontent.com/38277934/44783335-b2e92980-ab92-11e8-8481-866304ae6cee.png">

**Comment by heronism** [comment]
Maybe I met the same problem. I used the 1060 cards, the hash rate can promote to 1.06KH/s. But some times it drops to 500H/s above. I can't give the probability because I have a shorter observation time. But it seems that this is a frequent phenomenon.
So is there any one else who met the same problem. How can I fix it?

**Comment by Turcy086** [comment]
Same problem here. I have 6x1080. Two vga hashing around 1600-1700, anothers is 2000+

**Comment by Crowbcat** [comment]
@heronism, @Turcy086 

I've been able to catch several rigs choking on connection with the pool. At time, ping was 1900-2500ms.

Probably, there's a problem with the connection. Will try other pools. I'm closing this issue.

<img width="623" alt="screen shot 2018-08-29 at 18 15 06" src="https://user-images.githubusercontent.com/38277934/44797366-b216be80-abb7-11e8-97a1-c0589a88fb22.png">

**Comment by Turcy086** [comment]
Dear Crowbat,
I tried two another pool, but same problem there. I tried two separeted miner at time, using of -d switch. Same error!
